# Generated by Django 6.0.5 on 2026-05-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaturas',
            name='horario',
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='dia_de_clase',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], default='Lunes', max_length=9, verbose_name='Dia'),
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='hora',
            field=models.TimeField(null=True, verbose_name='Hora de la clase'),
        ),
    ]
