# Generated by Django 6.0.5 on 2026-05-16 00:45

import apps.estudiantes.models as estudiantes_models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100, validators=[estudiantes_models.validar_correo])),
                ('codigo', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
