# Generated by Django 5.2 on 2026-05-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_alter_estudiantes_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
