# Generated by Django 6.0.5 on 2026-05-17 04:25

import docentes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docentes',
            options={'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AddField(
            model_name='docentes',
            name='sexo',
            field=models.CharField(default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='correo',
            field=models.CharField(max_length=100, unique=True, validators=[docentes.models.validar_correo], verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
    ]
