# Generated by Django 6.0.5 on 2026-05-17 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docentes', '0004_alter_docentes_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignaturas',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Codigo')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docentes.docentes', verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
    ]
