# Generated by Django 6.0.5 on 2026-05-17 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaturas', '0002_remove_asignaturas_horario_asignaturas_dia_de_clase_and_more'),
        ('estudiantes', '0004_alter_estudiantes_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='matriculas_sma',
            fields=[
                ('codigo', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asignaturas.asignaturas', verbose_name='ID Asignatura')),
                ('estudiante_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.estudiantes', verbose_name='ID Estudiante')),
            ],
        ),
    ]
