# Generated by Django 5.2 on 2026-06-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='calificacion',
            options={'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='criterio',
            options={'verbose_name': 'Criterio', 'verbose_name_plural': 'Criterios'},
        ),
        migrations.AlterModelOptions(
            name='notafinal',
            options={'verbose_name': 'Nota Final', 'verbose_name_plural': 'Notas Finales'},
        ),
    ]
