# Generated by Django 6.0.5 on 2026-05-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas_sma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matriculas_sma',
            options={'verbose_name': 'Matricula', 'verbose_name_plural': 'Matriculas'},
        ),
    ]
