# Generated by Django 6.0.5 on 2026-05-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas_sma', '0002_alter_matriculas_sma_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculas_sma',
            name='codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
