# Generated by Django 6.0.5 on 2026-05-17 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas_sma', '0003_alter_matriculas_sma_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculas_sma',
            name='estado',
            field=models.CharField(choices=[('A', 'Activa'), ('P', 'Pendiente'), ('C', 'Cancelada')], default='Acttiva', max_length=10, verbose_name='Estado de la matricula'),
        ),
        migrations.AddField(
            model_name='matriculas_sma',
            name='fecha_de_matricula',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
