# Generated by Django 6.0.5 on 2026-05-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas_sma', '0004_matriculas_sma_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriculas_sma',
            old_name='estudiante_id',
            new_name='estudiante',
        ),
    ]
