# Generated by Django 6.0.5 on 2026-05-17 03:59

import estudiantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiantes',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='codigo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Codigo estudiantil'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='correo',
            field=models.CharField(max_length=100, validators=[estudiantes.models.validar_correo], verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
    ]
