# Generated by Django 6.0.5 on 2026-05-17 04:03

import estudiantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_alter_estudiantes_options_estudiantes_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='correo',
            field=models.CharField(max_length=100, unique=True, validators=[estudiantes.models.validar_correo], verbose_name='Correo electronico'),
        ),
    ]
