# Generated by Django 6.0.5 on 2026-05-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_alter_estudiantes_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=1, verbose_name='Sexo'),
        ),
    ]
