# Generated by Django 6.0.5 on 2026-05-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_alter_docentes_options_docentes_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=1),
        ),
    ]
