# Generated by Django 5.2 on 2026-06-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0005_alter_docentes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
